config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout },
                                   controllers: { sessions: 'sessions' }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'admin#tests'
    
    resources :tests do
      patch :update_inline, on: :member
      
      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :gists, only: :index
    resources :badges
  end

  resources :badges, only: :index do
    get :user_badges, on: :collection
  end

  get 'contact-me', to: 'messages#new', as: 'new_message'
  post 'contact-me', to: 'messages#create', as: 'create_message'
end

app/models/badge.rb
class Badge < ApplicationRecord
  has_many :user_badges
  has_many :users, through: :user_badge
  belongs_to :rule
  validates :name, presence: true
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)
    if @badge.save
      redirect_to admin_badges_path
    else
      render :new
    end
  end

  def update
    if @badge.update(badge_params)
      redirect_to [:admin, @badge]
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy
    redirect_to admin_badges_path
  end

  private

  def badge_params
    params.require(:badge).permit(:name, :rule_id)
  end

  def find_badge
    @badge = Badge.find(params[:id])
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end

  def user_badges
    @badges = current_user.badges
  end
end

app/helpers/admin/badges_helper.rb
module Admin::BadgesHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle">
    <%= content_tag :span, badge.name %>
  </td>
  <td><%= link_to 'Show', admin_badge_path(badge) %></td>
  <td><%= link_to 'Edit', edit_admin_badge_path(badge) %></td>
  <td>
    <%= link_to 'Delete',
                admin_badge_path(badge),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
  </td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>
  <%= render 'shared/errors', resource: @badge %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name, id: :badge_name %>
  </p><br>

  <p>
    <%= form.label :image %>
    <%= form.text_field :image, id: :badge_image %>
  </p><br>

  <p>
    <%= form.label :rule_id %>
    <%= form.collection_select :rule_id, Rule.all, :id, :name, prompt: true %>
  </p><br>

  <p><%= form.submit %></p>
  </form>
<% end %>

app/views/admin/badges/edit.html.erb
<h1>Edit badge</h1>

<%= render 'form' %>
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1>All badges</h1>

<p>
  <%= link_to "New badge", new_admin_badge_path %>
</p>

<div>
  <%= render 'shared/errors', resource: @badge %>
</div>

<table class="table">
  <tr>
    <th class="sort-by-title pointer">
      <%= "Name" %>
    </th>
  </tr>
  
  <%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1>Create new badge</h1>

<%= render 'form' %>
<%= link_to 'Back', admin_badges_path %>

app/views/admin/badges/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag(@badge.image) %>
</p>

<%= link_to 'Edit', edit_admin_badge_path(@badge) %> |
<%= link_to 'Back', admin_badges_path %>